### ISSUE TITLE
Reich AAA and SAM trucks dual spawn turret when zeused

### ISSUE THREAD

**Issue by scooby78** [scooby78/160thSOR_OpFor#8]
It places the extra turret in the bottom left of the map.  

Only seems to happen when Zeus places one down. If placed in the editor it's ok.

**Comment by AmTheAgent** [comment]
I found last Wednesday it was spawning at least 10 extra empty Turrets bottom left of the map - another interesting thing was when I added Objects to Zeus it was adding around 1200 each time... Didn't see that last night though i must admit.

**Comment by scooby78** [comment]
Looks like this needs to be moved to a function

**Comment by scooby78** [comment]
The issue seems to have two layers,

1) Code runs globally
2) There is a locality issue on a dedicated server

**Comment by AmTheAgent** [comment]
Also neglected to mention that when you place the Truck Down in the Editor or in Zeus and Delete it, it actually leaves the Attached Gun behind but the truck deletes.

**Comment by scooby78** [comment]
yeah aware of that I'm looking at a solution to fix that but ultimately it's not really an issue as it won't be in the final mission..  It's an 3den thing due to the fact that scripts can now be called from the editor....
It's really only a cosmetic thing..

**Comment by scooby78** [comment]
Possibly fixed in https://github.com/scooby78/160thSOR_OpFor/commit/f277aa9299da5404820fc237324abd2de5e3ccff

Requires testing with multiple players on a dedi server

**Comment by scooby78** [comment]
Fixed in https://github.com/scooby78/160thSOR_OpFor/pull/10
